### ISSUE TITLE
[BUG] Tab separator missing after updating to FF 89, stand alone patcher

### ISSUE THREAD

**Issue by explor202** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#123]
When using the standalone patcher for multi-row tabs, the tab separator is no longer visible. When the patch is removed, the separator is visible. This happened on a previous version too but you were able to resolve it.

**Comment by Izheil** [comment]
By default Firefox doesn't have a tab separator, the only way you'd get a tab separator would be using the userchrome from this repository or your own changes... and the one from the dark theme from this repository doesn't seem to have the issue on my end, so... what code were you using for separators?

**Comment by explor202** [comment]
AFAIK, I've been using whatever you fixed in issue #98.

**Comment by Izheil** [comment]
I added some fixes for tab separators today, so the code from that bug and the one I pushed the first of June is obsolete.

This is the current tab separators code on userChrome from the proton folder:

``` CSS
/* Tab separators */
.tabbrowser-tab::after {
  content: "";
  max-height: calc(var(--tab-min-height) - 4px);
  width: 1px;
  display: flex;
  margin-top: 6px;
}

#main-window[lwt-toolbar-field-brighttext] .tabbrowser-tab:not([visuallyselected]):not([beforeselected-visible])::after {
  box-shadow: 2px 0 0 0 rgba(255,255,255,.2) !important}

#main-window:not([lwt-toolbar-field-brighttext]) .tabbrowser-tab:not([visuallyselected]):not([beforeselected-visible])::after {
  box-shadow: 2px 0 0 0 rgba(0,0,0,.2) !important}
```

To increase the size of the separators you'd have to change the 3rd 0 on the box-shadow rules so that it adds 1 extra pixel to the default pixel width (so for example `box-shadow: 2px 0 0 2px rgba(0,0,0,.2)` would give a 3px width).

If you also just want the tab separators without the theme, I made a [standalone version](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/CSS%20tweaks/Tabs/Tab-separators.as.css) with that code.

I'm still unsure of why multirow makes the tab separators dissapear for you, since the ones I pushed on proton release were just a border of tabs, which multirow doesn't touch since the fix of #98, but the new separator changes should hopefully show them back for you.

**Comment by explor202** [comment]
Thank you, that code worked to restore the separator. However, when the tab is not in focus, it almost appears there are 2 separators now. I've tried adjusting some of the settings, but it still appears that way. Once the tab is in focus, the separator appears as just one (or maybe it's just narrower?). 

![ScreenShot001](https://user-images.githubusercontent.com/13698250/120893218-b6c5f800-c5d7-11eb-8000-131ba82a94e0.jpg)

**Comment by Izheil** [comment]
Make sure to remove the old code for tab separators, or it will overlap like that.

Specifically the one from [this comment](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/issues/98#issuecomment-739649254) of #98.

**Comment by explor202** [comment]
> 
> 
> Make sure to remove the old code for tab separators and leave only the new one, or it will overlap like that.
> 
> Specifically the one from [this comment](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/issues/98#issuecomment-739649254) of #98.

Thank you, that worked like a charm!
